name: integration
on:
  push:
  workflow_dispatch:
jobs:
  checkout_actions:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v5
       - name: install java
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '21'
           cache: 'maven'
       - name: test the code
         run: mvn test
       - name: package the code
         run: mvn package
     
